name: Deploy

on: push
env:
  ITCH_USERNAME: Crashim03
  ITCH_GAME_ID: crashim03.itch.io/speedjam-9
jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version_hash: ${{ steps.get_version.outputs.version_hash }}
    steps:
      - name: Get Version
        id: get_version
        run: echo "::set-output name=version_hash::$(date +%s)"

  deploy:
    needs: version
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        channel:
          - windows
          - webgl
    name: Deploy - Itch.io ${{ matrix.channel }}
    steps:
      - uses: actions/download-artifact@v2.0.8
        with:
          name: ${{ matrix.channel }}
          path: build/${{ matrix.channel }}
      - uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.BUTLER_API_KEY}}
          gameData: ./build/${{ matrix.channel }}
          itchUsername: ${{env.ITCH_USERNAME}}
          itchGameId: ${{ env.ITCH_GAME_ID }}
          buildChannel: ${{ matrix.channel }}
          buildNumber: ${{ needs.version.outputs.version_hash }}
