name: Build and Deploy

on: push

env:
  GODOT_VERSION: 4.3
  EXPORT_NAME: the-drill
  PROJECT_PATH: ./
  ITCH_USERNAME: Crashim03
  ITCH_GAME_ID: crashim03.itch.io/speedjam-9

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-22.04
    container:
      image: barichello/godot-ci:4.3
    outputs:
      artifact-path: ${{ steps.upload.outputs.artifact-path }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          mkdir -v -p build/web
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Web" "$EXPORT_DIR/web/index.html"
      - name: Upload Artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: web
          path: build/web

  version:
    runs-on: ubuntu-latest
    needs: export-web
    outputs:
      version_hash: ${{ steps.get_version.outputs.version_hash }}
    steps:
      - name: Get Version
        id: get_version
        run: echo "::set-output name=version_hash::$(date +%s)"

  deploy:
    needs: [export-web, version]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        channel:
          - web
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.channel }}
          path: build/${{ matrix.channel }}
      - uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{ secrets.BUTLER_API_KEY }}
          gameData: ./build/${{ matrix.channel }}
          itchUsername: ${{ env.ITCH_USERNAME }}
          itchGameId: ${{ env.ITCH_GAME_ID }}
          buildChannel: ${{ matrix.channel }}
          buildNumber: ${{ needs.version.outputs.version_hash }}
